// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// wl_join_cpp
DataFrame wl_join_cpp(DataFrame wl_1, DataFrame wl_2, int referral_index);
RcppExport SEXP _BSOLwaitinglist_wl_join_cpp(SEXP wl_1SEXP, SEXP wl_2SEXP, SEXP referral_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type wl_1(wl_1SEXP);
    Rcpp::traits::input_parameter< DataFrame >::type wl_2(wl_2SEXP);
    Rcpp::traits::input_parameter< int >::type referral_index(referral_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(wl_join_cpp(wl_1, wl_2, referral_index));
    return rcpp_result_gen;
END_RCPP
}
// wl_schedule_cpp
DataFrame wl_schedule_cpp(DataFrame waiting_list, DateVector schedule, int referral_index, int removal_index, bool unscheduled);
RcppExport SEXP _BSOLwaitinglist_wl_schedule_cpp(SEXP waiting_listSEXP, SEXP scheduleSEXP, SEXP referral_indexSEXP, SEXP removal_indexSEXP, SEXP unscheduledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type waiting_list(waiting_listSEXP);
    Rcpp::traits::input_parameter< DateVector >::type schedule(scheduleSEXP);
    Rcpp::traits::input_parameter< int >::type referral_index(referral_indexSEXP);
    Rcpp::traits::input_parameter< int >::type removal_index(removal_indexSEXP);
    Rcpp::traits::input_parameter< bool >::type unscheduled(unscheduledSEXP);
    rcpp_result_gen = Rcpp::wrap(wl_schedule_cpp(waiting_list, schedule, referral_index, removal_index, unscheduled));
    return rcpp_result_gen;
END_RCPP
}
// wl_simulator_cpp
DataFrame wl_simulator_cpp(Nullable<Date> start_date_, Nullable<Date> end_date_, double demand, double capacity, Nullable<DataFrame> waiting_list_, double withdrawal_prob, bool detailed_sim);
RcppExport SEXP _BSOLwaitinglist_wl_simulator_cpp(SEXP start_date_SEXP, SEXP end_date_SEXP, SEXP demandSEXP, SEXP capacitySEXP, SEXP waiting_list_SEXP, SEXP withdrawal_probSEXP, SEXP detailed_simSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<Date> >::type start_date_(start_date_SEXP);
    Rcpp::traits::input_parameter< Nullable<Date> >::type end_date_(end_date_SEXP);
    Rcpp::traits::input_parameter< double >::type demand(demandSEXP);
    Rcpp::traits::input_parameter< double >::type capacity(capacitySEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type waiting_list_(waiting_list_SEXP);
    Rcpp::traits::input_parameter< double >::type withdrawal_prob(withdrawal_probSEXP);
    Rcpp::traits::input_parameter< bool >::type detailed_sim(detailed_simSEXP);
    rcpp_result_gen = Rcpp::wrap(wl_simulator_cpp(start_date_, end_date_, demand, capacity, waiting_list_, withdrawal_prob, detailed_sim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BSOLwaitinglist_wl_join_cpp", (DL_FUNC) &_BSOLwaitinglist_wl_join_cpp, 3},
    {"_BSOLwaitinglist_wl_schedule_cpp", (DL_FUNC) &_BSOLwaitinglist_wl_schedule_cpp, 5},
    {"_BSOLwaitinglist_wl_simulator_cpp", (DL_FUNC) &_BSOLwaitinglist_wl_simulator_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_BSOLwaitinglist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
