# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Join two waiting lists
#' @param wl_1 First waiting list
#' @param wl_2 Second waiting list
#' @param referral_index Integer index of referral column (0-based in C++)
#' @return Joined waiting list
#' @export
wl_join_cpp <- function(wl_1, wl_2, referral_index = 0L) {
    .Call(`_BSOLwaitinglist_wl_join_cpp`, wl_1, wl_2, referral_index)
}

wl_schedule_cpp <- function(waiting_list, schedule, referral_index = 0L, removal_index = 1L, unscheduled = FALSE) {
    .Call(`_BSOLwaitinglist_wl_schedule_cpp`, waiting_list, schedule, referral_index, removal_index, unscheduled)
}

wl_simulator_cpp <- function(start_date_ = NULL, end_date_ = NULL, demand = 10.0, capacity = 11.0, waiting_list_ = NULL, withdrawal_prob = NA_real_, detailed_sim = FALSE) {
    .Call(`_BSOLwaitinglist_wl_simulator_cpp`, start_date_, end_date_, demand, capacity, waiting_list_, withdrawal_prob, detailed_sim)
}

